use codeup_test_db;

INSERT INTO albums (artist, album_name, release_date, sales, genre)
VALUES('Michael Jackson', 'Thriller', 1982, 47.3, 'pop, rock, R&B'),
      ('Eagles', 'Their Greatest Hits', 1976, 41.2, 'country, rock, soft rock, folk rock'),
      ('Eagles', 'Hotel California', 1976, 31.5, 'soft rock'),
      ('Various artists', 'Grease Soundtrack', 1978, 14.4, 'rock and roll'),
      ('Led Zeppelin', 'Led Zepplin IV', 1971, 29.0, 'hard rock, heavy metal, folk rock'),
      ('Michael Jackson', 'Bad', 1987, 19.3, 'pop, funk, rock'),
      ('Alanis Morissette', 'Jagged Little Pill', 1995, 19.3, 'alternative rock'),
      ('Celine Dion', 'Falling into You', 1996, 20.2, 'pop, soft rock'),
      ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 1967, 18.2, 'rock'),
      ('Various artists', 'Dirty Dancing', 1987, 17.9, 'pop, rock, R&B'),
      ('Michael Jackson', 'Dangerous', 1991, 17.3, 'rock, funk, pop'),
      ('Adele', '21', 2011, 25.3, 'pop, soul'),
      ('Celine Dion', 'Let''s Talk About Love', 1997, 19.3, 'pop, soft rock'),
      ('The Beatles', '1', 2000, 23.4, 'rock'),
      ('ABBA', 'Gold: Greatest Hits', 1992, 23.0, 'pop, disco'),
      ('Madonna', 'The Immaculate Collection', 1990, 19.4,'pop, dance'),
      ('The Beatles', 'Abbey Road', 1969, 14.4, 'rock'),
      ('Bruce Springsteen', 'Born in the U.S.A', 1984, 19.6, 'heartland rock'),
      ('Dire Straits', 'Brothers in Arms', 1985, 17.7, 'roots rock, blues rock, soft rock'),
      ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 18.1, 'film score'),
      ('Metallica', 'Metallica', 1991, 25.2, 'heavy metal'),
      ('Nirvana', 'Nevermind', 1991, 25.2, 'grunge, alternative rock'),
      ('Pink Floyd', 'The Wall', 1979, 18.7, 'progressive rock'),
      ('Santana', 'Supernatural', 1999, 20.5, 'latin rock'),
      ('Guns N'' Roses', 'Appetite for Destructionr', 1987, 21.6, 'hard rock');